name: Build model-hub docker image v3

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      custom_tag:
        description: 'Custom tag (required)'
        required: true
        type: string

jobs:
  build-docker:
    name: Build Docker Image
    uses: sandsiv/workflows/.github/workflows/build-with-cache.yaml@v2
    with:
      image_name: model-hub
      dockerfile: Dockerfile-no-cuda
      build_type: tagged
      custom_tag: ${{ github.event_name == 'workflow_dispatch' && inputs.custom_tag || github.ref_name }}-no-cuda

    secrets: inherit
